#- name: Run java
#  ansible.builtin.import_role:
#    name: common
#    tasks_from: java

- name: Install Docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker

- name: Start App container
  containers.podman.podman_container:
    name: shipping
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/shipping
    state: started
    restart: true
    restart_policy: "always"
    ports:
      - "8080:8080"
    env:
      CART_ENDPOINT: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/shipping:CART_ENDPOINT token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      DB_HOST: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/shipping:DB_HOST token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"

- name: Schema containers
  loop:
    - app-user
    - schema
    - master-data
  containers.podman.podman_container:
    name: shipping-schema-{{item}}
    recreate: true
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: started
    env:
      DB_TYPE: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/shipping:DB_TYPE token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      APP_GIT_URL: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/shipping:APP_GIT_URL token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      DB_USER: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/shipping:DB_USER token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      DB_PASS: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/shipping:DB_PASS token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      SCHEMA_FILE: "db/{{ item }}.sql"
      DB_HOST: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/shipping:DB_HOST token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"