COMPONENT: cart
PROMETHEUS_MONITOR: yes
RSYSLOG_CONFIG: yes

lvm_sizes:
  - { volume: varVol, size: 12G }
  - { volume: rootVol, size: 6G }
  - { volume: homeVol, size: 960M }
  - { volume: logVol, size: 2G }
  - { volume: varTmpVol, size: 2G }
  - { volume: auditVol, size: 4.4G }