- name: Install Docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker

#echo "Update RoboShop Config File"
#for component in catalogue user cart payment shipping ; do
#sed -i -e "/$component/ s/localhost/${component}.roboshop.internal/" /etc/nginx/default.d/roboshop.conf &>>$LOG_FILE
#done
#  #sed -i -e '/catalogue/ s/localhost/catalogue.roboshop.internal/' -e '/user/ s/localhost/user.roboshop.internal/' -e '/cart/ s/localhost/cart.roboshop.internal/' -e '/payment/ s/localhost/payment.roboshop.internal/' -e '/shipping/ s/localhost/shipping.roboshop.internal/' /etc/nginx/default.d/roboshop.conf &>>$LOG_FILE
#StatusCheck $?

#- name: Install Nginx
#  ansible.builtin.yum:
#    name: nginx
#    state: installed
#
#- name: Start a nginx service
#  ansible.builtin.systemd_service:
#    state: started
#    name: nginx
#
#- name: Removing Old Web Content
#  ansible.builtin.file:
#    path: /usr/share/nginx/html
#    state: absent


#- name: Downloading Nginx Web Content & extract it
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
#    dest: /tmp
#    remote_src: yes
#
#- name: Copy extracted content
#  ansible.builtin.copy:
#    src: /tmp/frontend-main/static/
#    dest: /usr/share/nginx/html/
#    remote_src: yes

#- name: Create application directory
#  ansible.builtin.file:
#    path: /usr/share/nginx/html
#    state: directory
#
#- name: Downloading Application Content
#  ansible.builtin.unarchive:
#    src: http://{{NEXUS_USER}}:{{NEXUS_PASS}}@nexus.roboshop.internal:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
#    dest: /usr/share/nginx/html
#    remote_src: yes
#
#- name: Copy Nginx Service Config file
#  ansible.builtin.template:
#    src: nginx.conf
#    dest: /etc/nginx/nginx.conf
#  notify: Restart Nginx Service
#
#- name: Copy Roboshop config file
#  ansible.builtin.template:
#    src: roboshop.conf
#    dest: /etc/nginx/default.d/roboshop.conf
#  notify: Restart Nginx Service
#
#
#
#- name: Start a nginx service
#  ansible.builtin.systemd:
#    state: restarted
#    name: nginx
#    enabled: yes
#
#- name: Run filebeat
#  ansible.builtin.import_role:
#    name: elk
#    tasks_from: filebeat


- name: Start App container
  containers.podman.podman_container:
    name: frontend
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
    state: started
    restart: true
    restart_policy: "always"
    ports:
      - "80:80"
    env:
      CATALOGUE_HOST: "{{ lookup('hashi_vault', 'roboshop/data/frontend:CATALOGUE_HOST token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      CATALOGUE_PORT: "{{ lookup('hashi_vault', 'roboshop/data/frontend:CATALOGUE_PORT token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      USER_HOST: "{{ lookup('hashi_vault', 'roboshop/data/frontend:USER_HOST token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      USER_PORT: "{{ lookup('hashi_vault', 'roboshop/data/frontend:USER_PORT token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      CART_HOST: "{{ lookup('hashi_vault', 'roboshop/data/frontend:CART_HOST token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      CART_PORT: "{{ lookup('hashi_vault', 'roboshop/data/frontend:CART_PORT token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      SHIPPING_HOST: "{{ lookup('hashi_vault', 'roboshop/data/frontend:SHIPPING_HOST token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      SHIPPING_PORT: "{{ lookup('hashi_vault', 'roboshop/data/frontend:SHIPPING_PORT token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      PAYMENT_HOST: "{{ lookup('hashi_vault', 'roboshop/data/frontend:PAYMENT_HOST token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      PAYMENT_PORT: "{{ lookup('hashi_vault', 'roboshop/data/frontend:PAYMENT_PORT token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
