- name: Add the application user
  ansible.builtin.user:
    name: roboshop
  register: appuser

- name: Clean UP old App Content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

#- name: Downloading application code & extract it
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
#    dest: /tmp
#    remote_src: yes

- name: Create Application Directory
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}-tmp
    state: directory
    owner: roboshop
    group: roboshop

- name: Downloading Application Content
  ansible.builtin.unarchive:
    src: http://{{NEXUS_USER}}:{{NEXUS_PASS}}@nexus.roboshop.internal:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /home/roboshop/{{COMPONENT}}-tmp
    remote_src: yes
  become_user: roboshop


#
#- name: Copy extracted content
#  ansible.builtin.copy:
#    src: /tmp/{{COMPONENT}}-main/
#    dest: /home/roboshop/{{COMPONENT}}/
#    remote_src: yes
#  become_user: roboshop
