#echo "Setting nodejs Repo"
#curl -sL https://rpm.nodesource.com/setup_lts.x | bash &>>${LOG_FILE}
#StatusCheck $?
#
#echo "install nodejs"
#yum install nodejs -y &>>${LOG_FILE}
#StatusCheck $?
#
#APP_PREREQ
#
#echo "inatall Nodejs dependencies"
#npm install &>>LOG_FILE0
#StatusCheck $?
#
#SYSTEMD_SETUP

- name: Setting nodejs Repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed



- name: Include task list in play
  ansible.builtin.import_tasks: App-prereq.yml
