
#APP_UID=$(id -u roboshop)
#APP_GID=$(id -g roboshop)
#
#echo "Update Payment Configuration file"
#sed -i -e "/uid/ c uid = ${APP_UID}" -e "/gid/ c gid = ${APP_GID}" /home/roboshop/${COMPONENT}/${COMPONENT}.ini &>>${LOG_FILE}
#StatusCheck $?
#
#SYSTEMD_SETUP

- name: Install Pyhton
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python36-devel
    state: installed

- name: Import App Pre-Req Task file
  ansible.builtin.import_tasks: App-prereq.yml


- name: Install PIP requirements file
  ansible.builtin.pip:
    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
    executable: pip3

- name: Change UID & GID in App configuration
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^{{item.name}}'
    line: uid = {{item.id}}
  loop:
    - { name: "uid", id: "{{appuser.uid}}"}
    - { name: "gid", id: "{{appuser.group}}"}

- name: Import SystemD tasks
  ansible.builtin.import_tasks: systemd.yml
