#echo "Update SystemD Service File"
#sed -i -e 's/REDIS_ENDPOINT/redis.roboshop.internal/' -e 's/MONGO_ENDPOINT/mongodb.roboshop.internal/' -e 's/CATALOGUE_ENDPOINT/catalogue.roboshop.internal/' -e 's/MONGO_DNSNAME/mongodb.roboshop.internal/' -e 's/CARTENDPOINT/cart.roboshop.internal/' -e 's/DBHOST/mysql.roboshop.internal/' -e 's/DBHOST/mysql.roboshop.internal/' -e 's/CARTENDPOINT/cart.roboshop.internal/' -e 's/CARTHOST/cart.roboshop.internal/' -e 's/USERHOST/user.roboshop.internal/' -e 's/AMQPHOST/rabbitmq.roboshop.internal/' /home/roboshop/${COMPONENT}/systemd.service
#StatusCheck $?
#
#echo "setup ${COMPONENT} service"
#mv /home/roboshop/${COMPONENT}/systemd.service /etc/systemd/system/${COMPONENT}.service &>>${LOG_FILE}
#StatusCheck $?
#
#systemctl daemon-reload &>>${LOG_FILE}
#systemctl enable ${COMPONENT} &>>${LOG_FILE}
#
#echo "start ${COMPONENT} service"
#systemctl start ${COMPONENT} &>>${LOG_FILE}
#StatusCheck $?

- name: Copy {{COMPONENT}}.service file
  ansible.builtin.copy:
    src: "{{COMPONENT}}.service"
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Start a {{COMPONENT}} service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    enabled: yes
    daemon-reload: yes
    state: restarted