#- name: Run NodeJS
#  ansible.builtin.import_role:
#    name: common
#    tasks_from: nodejs


- name: Install Docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker

- name: Start App container
  containers.podman.podman_container:
    name: catalogue
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
    state: started
    restart: true
    restart_policy: "always"
    ports:
      - "8080:8080"
    env:
      MONGO: "{{ lookup('hashi_vault', 'roboshop/data/catalogue:MONGO token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      MONGO_URL: "{{ lookup('hashi_vault', 'roboshop/data/catalogue:MONGO_URL token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"

- name: Schema container
  containers.podman.podman_container:
    name: catalogue-schema
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: started
    env:
      DB_TYPE: "{{ lookup('hashi_vault', 'roboshop/data/catalogue:DB_TYPE token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      APP_GIT_URL: "{{ lookup('hashi_vault', 'roboshop/data/catalogue:APP_GIT_URL token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      DB_HOST: "{{ lookup('hashi_vault', 'roboshop/data/catalogue:DB_HOST token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"
      SCHEMA_FILE: "{{ lookup('hashi_vault', 'roboshop/data/catalogue:SCHEMA_FILE token={{ vault_token }} url=http://vault-internal.surendraalamuru22.online:8200')}}"


