- name: Set Prompt
  ansible.builtin.shell: set-prompt {{COMPONENT}}-{{env}}

#- name: Install prometheus node-exporter
#  ansible.builtin.shell: labauto prometheus-node-exporter
#  when: PROMETHEUS_MONITOR | bool
#
#- name: Setup Rsyslog Config
#  when: RSYSLOG_CONFIG | bool
#  ansible.builtin.import_role:
#    name: elk
#    tasks_from: rsyslog

- name: Increase disk partition
  ansible.builtin.shell: growpart /dev/nvme0n1 4
  ignore_errors: yes

- name: Extend LV
  ansible.builtin.shell: lvextend -r -L {{item.size}} /dev/mapper/RootVG-{{ item.volume }}
  ignore_errors: yes
  loop: "{{ lvm_sizes }}"