COMPONENT: mysql
SECRETS: "{{lookup('amazon.aws.aws_secret', 'roboshop/all-secrets', region='us-east-1')}}"
ROBOSHOP_MYSQL_PASSWORD: "{{SECRETS.ROBOSHOP_MYSQL_PASSWORD}}"

lvm_sizes:
  - { volume: varVol, size: 12G }
  - { volume: rootVol, size: 6G }
  - { volume: homeVol, size: 960M }
  - { volume: logVol, size: 2G }
  - { volume: varTmpVol, size: 2G }
  - { volume: auditVol, size: 4.4G }