- name: copy prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart prometheous
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Wait for prometheus port open
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 30


